### ISSUE TITLE
ResourceOwnerId returning NULL value

### ISSUE THREAD

**Issue by briward** [chrishemmings/oauth2-drupal#5]
Hi there,

Thanks for creating the provider.

I'm using "authorization_code" grant and i've created a scope called "basic" (default) however the returned value is "insufficient_scope" which may be due to the fact the token returns without a resource owner ID (NULL). 

Have you encountered this before and perhaps know of the solution?

Best wishes,
Bri

**Comment by chrishemmings** [comment]
Hey there,

No this is not something I have come across to be honest.  I'm unlikely to be able to get this issue reproduced anytime soon.  If you have more information on this, please get back to me.
